### Linear Regression Parameter Estimation example with Gradient Descent

Recall our discussion on cost function for linear regression, it looked like this:

$$
SSE = \sum e_i^2 = \sum (y_i - \hat{y}_i)^2 = \sum (y_i - \beta_0 - \beta_1 x_i)^2
$$

If we consider entire $X,Y$ data and parameters $\beta$s to be written in matrix format like this:

$$
Y = \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n
\end{bmatrix}
$$

$$
X = \begin{bmatrix}
1 & x_{11} & x_{21} & \cdots & x_{p1} \\
1 & x_{12} & x_{22} & \cdots & x_{p2} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{1n} & x_{2n} & \cdots & x_{pn}
\end{bmatrix}
$$

$$
\beta = \begin{bmatrix}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_p
\end{bmatrix}
$$

### Linear Regression Parameter Estimation with Gradient Descent

#### Cost Function (SSE)
The sum of squared errors is defined as:

$$
SSE = \sum e_i^2 = \sum (y_i - \hat{y}_i)^2 = \sum (y_i - \beta_0 - \beta_1 x_i)^2
$$

In matrix notation:
$$
SSE = (y - X\beta)^T(y - X\beta)
$$

#### Matrix Definitions
$$
Y = \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
1 & x_{11} & \cdots & x_{p1} \\
1 & x_{12} & \cdots & x_{p2} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_{1n} & \cdots & x_{pn}
\end{bmatrix}, \quad
\beta = \begin{bmatrix}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_p
\end{bmatrix}
$$


1. Prediction equation:
   $$
   X\beta \rightarrow \text{predicted values}
   $$

2. Residual calculation:
   $$
   Y - X\beta \rightarrow \text{error vector}
   $$

3. Cost function in matrix form:
   $$
   (Y - X\beta)^T(Y - X\beta) = \text{SSE}
   $$

4. Gradient of SSE:
   $$
   \nabla_\beta SSE = -2X^T(Y - X\beta)
   $$

#### Gradient Descent Update Rule
At each iteration:
$$
\beta_{new} = \beta_{old} - \eta \nabla_\beta SSE
$$
Where:
- $\eta$ is the learning rate
- $\nabla_\beta SSE$ is the gradient computed above

#### Implementation Steps
1. Initialize $\beta$ with random values
2. Compute predictions: $\hat{y} = X\beta$
3. Calculate errors: $e = y - \hat{y}$
4. Compute gradient: $\nabla_\beta = -2X^Te$
5. Update parameters: $\beta = \beta - \eta \nabla_\beta$
6. Repeat until convergence

#### Convergence Criteria
The algorithm stops when either:
- $\|\nabla_\beta\| < \epsilon$ (small threshold)
- Maximum iterations reached
- Change in SSE between iterations becomes negligible

$$
Prediction=\hat{Y}=X\beta = \begin{bmatrix}
1 & x_{11} & \cdots & x_{p1} \\
1 & x_{12} & \cdots & x_{p2} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_{1n} & \cdots & x_{pn}
\end{bmatrix}
\begin{bmatrix}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_p
\end{bmatrix}
$$

$$
\hat{Y} = \begin{bmatrix}
1\cdot\beta_0 + x_{11}\cdot\beta_1 + \cdots + x_{p1}\cdot\beta_p \\
1\cdot\beta_0 + x_{12}\cdot\beta_1 + \cdots + x_{p2}\cdot\beta_p \\
\vdots \\
1\cdot\beta_0 + x_{1n}\cdot\beta_1 + \cdots + x_{pn}\cdot\beta_p
\end{bmatrix}
$$

This results in a vector of predicted values, where each element corresponds to the predicted value for a single data point.

---

$$
\text{Error} = Y - X\beta
$$

$$
Error = \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n
\end{bmatrix} - \left( \begin{bmatrix}
1 & x_{11} & \cdots & x_{p1} \\
1 & x_{12} & \cdots & x_{p2} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_{1n} & \cdots & x_{pn}
\end{bmatrix}
\begin{bmatrix}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_p
\end{bmatrix} \right)
$$

$$
Error = \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n
\end{bmatrix} - \begin{bmatrix}
1\cdot\beta_0 + x_{11}\cdot\beta_1 + \cdots + x_{p1}\cdot\beta_p \\
1\cdot\beta_0 + x_{12}\cdot\beta_1 + \cdots + x_{p2}\cdot\beta_p \\
\vdots \\
1\cdot\beta_0 + x_{1n}\cdot\beta_1 + \cdots + x_{pn}\cdot\beta_p
\end{bmatrix}
$$

$$
Error = \begin{bmatrix}
y_1 - (1\cdot\beta_0 + x_{11}\cdot\beta_1 + \cdots + x_{p1}\cdot\beta_p) \\
y_2 - (1\cdot\beta_0 + x_{12}\cdot\beta_1 + \cdots + x_{p2}\cdot\beta_p) \\
\vdots \\
y_n - (1\cdot\beta_0 + x_{1n}\cdot\beta_1 + \cdots + x_{pn}\cdot\beta_p)
\end{bmatrix} = \begin{bmatrix}
e_1 \\
e_2 \\
\vdots \\
e_n
\end{bmatrix} = e
$$

This results in a vector of errors, where each element is the difference between the actual value and the predicted value for a single data point.

In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=20000)
x2=np.random.randint(low=1,high=20,size=20000)

In [3]:
y=3+2*x1-4*x2+np.random.random(20000)

you can see that we have generated data such that y is an approximate linear combination of x1 and x2, next we'll calculate optimal parameter values using gradient descent and compare them with results from sklearn and we'll see how good is the method.

In [4]:
x=pd.DataFrame({'intercept':np.ones(x1.shape[0]),'x1':x1,'x2':x2})
w=np.random.random(x.shape[1])

In [5]:
y

array([ 23.13792683, -20.18992061,   1.10753345, ...,  29.26322215,
       -66.34913842, -60.2879041 ])

#### Lets write functions for predictions, error, cost and gradient that we discussed above

##### 1. Prediction

In [8]:
def myprediction(features,weights):
    predictions=np.dot(features,weights) ## function numpy.dot : is used for matrix multiplication
    return(predictions)
myprediction(x,w)

array([15.13518179, 12.67216884,  6.83351855, ..., 15.63173257,
        7.68692004,  6.41593163])

##### 2. Error

In [9]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)
myerror(y,x,w)

array([  8.00274504, -32.86208945,  -5.72598511, ...,  13.63148958,
       -74.03605846, -66.70383573])

##### 3. Loss/Cost Function

In [10]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)
mycost(y,x,w)

np.float64(26785821.910174765)

##### 4. Gradient of Loss

In [11]:
def gradient(target,features,weights):
    error=myerror(target,features,weights)
    gradient=-np.dot(features.T,error)/features.shape[0]
    return(gradient)
gradient(y,x,w)

array([ 27.22707814, 233.95898948, 402.00693839])

- Note that gradient here is vector of 3 values because there are 3 parameters . Also since this is being evaluated on the entire data, we scaled it down with number of observations . Do recall that , the approximation which led to the ultimate results was that change in parameters is small. We dont have any direct control over gradient , we can always chose a small value for $\eta$ to ensure that change in parameter remains small. Also if we end up chosing too small value for $\eta$, we'll need to take larger number of steps to change in parameter in order to arrive at the optimal value of the parameters


**Lets looks at the expected value for parameters from sklearn . Dont worry about the syntax here , we'll discuss that in detail, when we formally start with linear models in next module/Lecture .**

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lr=LinearRegression()
lr.fit(x.iloc[:,1:],y)
sk_estimates=([lr.intercept_]+list(lr.coef_))

In [14]:
sk_estimates

[np.float64(3.4992084121435383),
 np.float64(1.9997501123748274),
 np.float64(-3.999658633868609)]

When you run the same , these might be different for you, as we generated the data randomly

#### Now lets write our version of this , using gradient descent

In [15]:
def my_lr(target,features,learning_rate,num_steps,print_when):

    # start with random values of parameters
    weights=np.random.random(features.shape[1])

    # change parameter multiple times in sequence
    # using the cost function gradient which we discussed earlier
    for i in range(num_steps):

        weights =weights- learning_rate*gradient(target,features,weights)

    # this simply prints the cost function value every (print_when)th iteration
        if i%print_when==0:
            print(mycost(target,features,weights),weights)

    return(weights)

In [16]:
my_lr(y,x,.0001,500,10)

34532015.67046891 [0.6051539  0.92387787 0.59690049]
24710121.062121555 [0.5759674  0.66893269 0.17102219]
18374086.185818285 [ 0.5529527   0.48223191 -0.18121298]
14233481.138368469 [ 0.53482384  0.34910705 -0.47469547]
11478878.032792915 [ 0.52056273  0.25795879 -0.7212273 ]
9602363.894890811 [ 0.5093634   0.19961717 -0.93016508]
8285041.1582575375 [ 0.50058776  0.16683516 -1.10892898]
7326514.18275353 [ 0.49373065  0.15388772 -1.26340575]
6600691.52223081 [ 0.48839216  0.15625436 -1.39826779]
6028082.258197277 [ 0.48425568  0.17036788 -1.51722574]
5558430.444725748 [ 0.48107056  0.19341543 -1.62322848]
5159829.283368368 [ 0.4786384   0.22318105 -1.71862151]
4811896.700032572 [ 0.47680209  0.25792099 -1.80527226]
4501496.579963767 [ 0.47543729  0.29626503 -1.88466941]
4220055.631063833 [ 0.47444555  0.33713835 -1.95800146]
3961880.4193658573 [ 0.47374894  0.37969973 -2.02621897]
3723101.357282534 [ 0.47328577  0.42329257 -2.09008384]
3501009.7171368822 [ 0.47300722  0.46740616 -2.150

array([ 0.48392881,  1.50665309, -3.24715025])

In [19]:
print(sk_estimates)

[np.float64(3.4992084121435383), np.float64(1.9997501123748274), np.float64(-3.999658633868609)]


- you can see that if we take too few steps , we did not reach to the optimal value.
- Lets increase the learning rate $\eta$

In [20]:
my_lr(y,x,.01,500,10)

23389875.033597946 [ 0.11976344 -1.21799464 -3.35836761]
4095597047.7425246 [ -1.54191766 -18.88094798 -24.87771922]
890778349496.3228 [ -26.64405545 -307.10496343 -314.58821204]
193742740198188.44 [ -397.41668255 -4558.5088672  -4586.4137325 ]
4.213870999945231e+16 [ -5866.06845981 -67257.45439613 -67586.49321834]
9.165096348118702e+18 [ -86517.32933034 -991930.34453477 -996700.45262407]
1.993392561648011e+21 [ -1275948.35017788 -14628841.8906572  -14699108.09982173]
4.3355942522625986e+23 [-1.88174664e+07 -2.15743592e+08 -2.16779783e+08]
9.429842310995687e+25 [-2.77516659e+08 -3.18174820e+09 -3.19702968e+09]
2.050974349452536e+28 [-4.09276641e+09 -4.69238575e+10 -4.71492259e+10]
4.460833642156739e+30 [-6.03593922e+10 -6.92024717e+11 -6.95348411e+11]
9.702235812119734e+32 [-8.90169597e+11 -1.02058576e+13 -1.02548749e+13]
2.110219463563442e+35 [-1.31280631e+13 -1.50514176e+14 -1.51237074e+14]
4.58969073792193e+37 [-1.93610344e+14 -2.21975634e+15 -2.23041750e+15]
9.982497760775227e+39 [

array([2.58814163e+57, 2.96732275e+58, 2.98157437e+58])

You can see that because of high learning rate , change is parameter is huge and we end up missing the optimal point , cost function values , as well as parameter values ended up exploding. Now lets run with low learning rate and higher number of steps

In [21]:
my_lr(y,x,.0004,100000,1000)

25574783.82825318 [0.70964133 0.05579706 0.53542758]
21283.562193351743 [ 0.75550049  2.11972474 -3.88089352]
19349.647105502303 [ 0.8942895   2.11367155 -3.88691677]
17606.43595106173 [ 1.02605792  2.10790889 -3.89261976]
16035.12309290925 [ 1.15116092  2.10243774 -3.89803426]
14618.757615952734 [ 1.26993564  2.09724334 -3.90317488]
13342.060137213162 [ 1.38270221  2.0923117  -3.90805546]
12191.25797580888 [ 1.48976454  2.08762952 -3.91268915]
11153.936576850552 [ 1.59141118  2.08318419 -3.91708846]
10218.905586446532 [ 1.68791608  2.07896372 -3.92126523]
9376.078133071082 [ 1.77953933  2.07495674 -3.92523071]
8616.362013013495 [ 1.86652787  2.07115245 -3.92899561]
7931.561606045468 [ 1.94911614  2.0675406  -3.93257006]
7314.289463198152 [ 2.02752673  2.06411146 -3.9359637 ]
6757.886612881024 [ 2.10197096  2.06085577 -3.93918568]
6256.350725625576 [ 2.17264947  2.05776478 -3.94224467]
5804.271362513569 [ 2.23975274  2.05483014 -3.94514892]
5396.7716087666995 [ 2.30346163  2.05204394 -

array([ 3.4831191 ,  2.00045375, -3.99896228])

We can see here that we ended up getting pretty good estimates for $\beta$s, as good as from sklearn.

In [22]:
sk_estimates

[np.float64(3.4992084121435383),
 np.float64(1.9997501123748274),
 np.float64(-3.999658633868609)]

there are modifications to gradient descent which can achieve the same thing in much less number of iterations. We'll discuss that in detail when we start with our course in Deep learning. For now ,we'll conclude this module